services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - my_network
    volumes:
      - ./data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - my_network
  storage:
    image: redis
    volumes:
      - ./data:/data
    networks:
      - my_network
  library:
    image: node:20.10
    working_dir: /app
    volumes:
      - ./library:/app
    ports:
      - 3000:3000
    command: npm start
    networks:
      - my_network
  counter:
    image: node:20.10
    working_dir: /app
    volumes:
      - ./counter:/app
    environment:
      - REDIS_URL=redis://storage
    ports:
      - 4000:4000
    command: npm start
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
